"""Bundle ui/fixtures/*.json into ui/dist/fixtures.js.

Why this exists: the app must open by double-clicking ui/dist/index.html. Under the
file:// origin every browser blocks fetch() of sibling JSON files (opaque origin), so
reading the fixtures at runtime would fail exactly where we promised it would not.
A plain <script> tag has no such restriction, so the fixtures are emitted as one
assignment to window.REALDOOR_FIXTURES.

The JSON is copied verbatim. Nothing is reshaped, renamed, or summarised here --
if a number is wrong on screen it is wrong in the pipeline output, not in this file.

Run:  python ui/tools/build_fixtures.py
"""
from __future__ import annotations

import json
from pathlib import Path

UI = Path(__file__).resolve().parent.parent
FIXTURES = UI / "fixtures"
OUT = UI / "dist" / "fixtures.js"


def main() -> None:
    bundle = {}
    for path in sorted(FIXTURES.glob("*.json")):
        bundle[path.stem] = json.loads(path.read_text(encoding="utf-8"))

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(bundle, ensure_ascii=False, indent=1, sort_keys=False)
    OUT.write_text(
        "/* GENERATED by ui/tools/build_fixtures.py -- do not edit by hand.\n"
        "   Verbatim copy of ui/fixtures/*.json, keyed by file stem. */\n"
        "window.REALDOOR_FIXTURES = " + body + ";\n",
        encoding="utf-8",
    )
    print(f"[ui] wrote {OUT} ({OUT.stat().st_size:,} bytes, {len(bundle)} fixtures)")
    for key in bundle:
        print(f"      - {key}")


if __name__ == "__main__":
    main()
